name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt update && sudo apt -y install tar curl xz-utils make cmake && sudo apt clean && cd /opt && sudo curl -L "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz?revision=79f65c42-1a1b-43f2-acb7-a795c8427085&la=en&hash=3BEE623628664E6E1736ABBE7CE5AD76B65B51EA" | sudo tar -Jxf -
    - name: prepare
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchain.cmake ..
    - name: compilation
      run: make image